apiVersion: v1
kind: Service
metadata:
  name: kubernetes-backend
spec:
  selector:
    app: kubernetes
  ports:
    - port: 80
      targetPort: 9090
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
      - name: kubecontainer
        image: agustingomezdev/backendcoderhouse:1.0.0
        ports:
          - containerPort: 9090
        env:
          - name: MONGO
            value: mongodb+srv://CoderUser:1234@ecommerce.5odsxhx.mongodb.net/?retryWrites=true&w=majority
          - name: JWT_KEY
            value: "SecretCoderKey"
          - name: JWT_RESET_PASSWORD_KEY
            value: "d942738b"
          - name: JWT_COOKIE_KEY
            value: "jwtCookieToken"
          - name: GITHUB_CLIENT_ID
            value: "Iv1.5221eb12b0627adf"
          - name: GITHUB_CLIENT_SECRET
            value: "7ac8095c895540f5450a2094ea998cac545dbf99"
          - name: GITHUB_CALLBACK_URL
            value: "http://localhost:8080/api/sessions/githubcallback"
          - name: ADMIN_EMAIL
            value: "adminCoderhouse@gmail.com"
          - name: ADMIN_PASSWORD
            value: "adminCoderhouse"
          - name: PERSISTENCE
            value: "MONGO"
          - name: NODEMAILER_GMAIL
            value: "agustingomezdev@gmail.com"
          - name: NODEMAILER_PASS
            value: "ilaasjsirahxzsac"
        imagePullPolicy: Always
